image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: RiceNet.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:test -filter:"+[RiceNet*]* -[RiceNetTests*]*" -output:"./RiceNet_coverage.xml" -oldstyle
- codecov -f "RiceNet_coverage.xml